apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
        - name: pricing-service
          image: chaitanya2012/pricing-service # Change to your Docker Hub image
          ports:
            - containerPort: 8093
      imagePullSecrets:
        - name: docker-hub-secret
