apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
        - name: pricing-service
          image: chaitanya2012/pricing-service:a8105d8676488bf99432db7101f3517c672356d0
          ports:
            - containerPort: 8093
      imagePullSecrets:
        - name: docker-hub-secret
