apiVersion: v1
kind: Service
metadata:
  name: pricing-service-service
spec:
  selector:
    matchLabels:
      app: pricing-service # Replace with your deployment's label
  ports:
    - protocol: TCP
      port: 8093         # Service port
      targetPort: 8093  # Port on the container
  type: ClusterIP     # Use LoadBalancer or NodePort if external access is needed
