apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-services
  template:
    metadata:
      labels:
        app: car-services
    spec:
      containers:
        - name: car-services
          image: chaitanya2012/car-services:f8a5eda0d0319c587f3412aa828442d0b0091862 # Change to your Docker Hub image
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: docker-hub-secret
