apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-services
  template:
    metadata:
      labels:
        app: car-services
    spec:
      containers:
        - name: car-services
          image: chaitanya2012/car-services:e240f49489efff7f18e5c4afbf0aab5407d77a07 # Change to your Docker Hub image
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: docker-hub-secret
