apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"car-service-service","namespace":"car-auction-project"},"spec":{"ports":[{"port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"car-services"},"type":"ClusterIP"}}
  creationTimestamp: "2025-03-15T05:15:43Z"
  name: car-service-service
  namespace: car-auction-project
  resourceVersion: "3117"
  uid: 0a497130-4901-4826-9b1c-b6f66bf087b2
spec:
  clusterIP: 10.100.173.48
  clusterIPs:
  - 10.100.173.48
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: car-services
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
